version: 2.1
jobs:
  job1:
    docker:
      - image: circleci/node:10
      - image: mongo:2.6.8
#        entrypoint: ["echo"]
#        command: ["this is test"]

      - image: postgres:9.4.1


    steps:
      - run: |
          echo '#!/bin/sh' > run.sh
          echo 'echo Hello world!' >> run.sh
          chmod +x run.sh
      - run: ./run.sh
      - nc -vz hocalhost 27017


  job2:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
#                docker_layer_caching: true

#       install docker-compose
#      - run:
#          name: Install Docker Compose
#          command: |
#            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
#            chmod +x ~/docker-compose
#            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: Start container and verify it is working
          command: |
            set -x
            docker-compose up -d



      #      - run: |
      #          TAG=0.1.$CIRCLE_BUILD_NUM
      #          docker build -t circleci-public/circleci-demo-docker:$TAG .
      #          echo $DOCKERHUB_PASSWORD | docker login -username $DOCKERHUB_USERNAME --password-stdin
      #          docker push circleci-public/circleci-demo-docker:$TAG



  job3:
    docker:
      - image: 20200812/circlecidemo:v3
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: echo this is auth test

  job4:
    docker:
      - image: circleci/node:10

    steps:
      - setup_remote_docker:
          version: 18.06.0-ce

      - checkout

      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t circleci-public/circleci-demo-docker:$TAG .
          docker images
#          echo $DOCKERHUB_PASSWORD | docker login -username $DOCKERHUB_USERNAME --password-stdin
#          docker push circleci-public/circleci-demo-docker:$TAG



  job5:
    docker:
      - image: 20200812/circlecidemo:v3
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        entrypoint: echo test


    steps:
      - run: echo this is label test


workflows:
  test_flow:
    jobs:
      - job1
